[project]
name = "spec-u-llm"
version = "0.1.0"
description = "Using LLMs to update the Filecoin specification. A Fast Phil experiment from the 2024 Chiang Mai Filecoin Hacker House."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv]
package = true
